export const sankeyData = {
  nodes: [
    { name: "Community Relations" },
    { name: "We are making good progress" },
    { name: "We are not making enough progress" },
    { name: "I am not aware of work in this area" },
    { name: "This is a Priority" },
    { name: "This is not a Priority" },
    { name: "SDG 5 - Gender Equality" },
    { name: "SDG 8 - Decent Work and Economic Growth" },
    { name: "SDG 9 - Industry, Innovation, and Infrastructure" },
    { name: "SDG 4 - Quality Education" },
    { name: "SDG 12 - Responsible Consumption and Production" },
    { name: "SDG 1 - No Poverty" },
    { name: "SDG 3 - Good Health and Well-Being" },
  ],
  links: [
    { source: 0, target: 1, value: 37 },
    { source: 0, target: 2, value: 23 },
    { source: 0, target: 3, value: 40 },
    { source: 1, target: 4, value: 82 },
    { source: 1, target: 5, value: 18 },
    { source: 2, target: 4, value: 71 },
    { source: 2, target: 5, value: 29 },
    { source: 3, target: 4, value: 68 },
    { source: 3, target: 5, value: 32 },
    { source: 4, target: 6, value: 26 },
    { source: 4, target: 7, value: 31 },
    { source: 4, target: 8, value: 19 },
    { source: 4, target: 9, value: 8 },
    { source: 4, target: 10, value: 3 },
    { source: 4, target: 11, value: 1 },
    { source: 4, target: 12, value: 1 },
    { source: 5, target: 6, value: 35 },
    { source: 5, target: 7, value: 18 },
    { source: 5, target: 8, value: 13 },
    { source: 5, target: 9, value: 18 },
    { source: 5, target: 10, value: 8 },
  ],
};
